name: CI Workflow

on:
  push:
    # trigger on all branches except for dependabot-triggered push events
    branches-ignore: [ dependabot/** ]
    tags:
      - 'v*'    # trigger on all tags
    paths-ignore:
      - '**.md' # ignore changes in markdown files
  pull_request:
    branches: [ develop ]
    types: [ opened, synchronize, reopened ]

jobs:
  test:
    name: Run tests (Node v${{ matrix.node-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18.19, 20.9]

    steps:
      - name: Checkout repo
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # ratchet:actions/checkout@v4.1.4
        with:
          fetch-depth: 0  # Get all history and branches

      - name: Set up node ${{ matrix.node-version}}
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # ratchet:actions/setup-node@v4.0.2
        with:
          node-version: ${{ matrix.node-version }}

      - name: yarn install dependencies
        run: |
          yarn install --ignore-engines

      - name: Run CI tests
        run: |
          yarn test

      - name: Test build
        continue-on-error: false
        run: |
          yarn build
