name: CI Workflow

on:
  push:
    # trigger on all branches except for dependabot-triggered push events
    branches-ignore: [ dependabot/** ]
    tags:
      - 'v*'    # trigger on all tags
    paths-ignore:
      - '**.md' # ignore changes in markdown files
  pull_request:
    branches: [ develop ]
    types: [ opened, synchronize, reopened ]

jobs:
  test:
    name: Run tests (Node v${{ matrix.node-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.19, 16.15, 18.x]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Get all history and branches

      - name: Set up node ${{ matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: yarn install dependencies
        run: |
          yarn install --ignore-engines

      - name: Run CI tests
        run: |
          yarn test

      - name: Test build
        run: |
          yarn build
