name: CI Workflow

on:
  push:
    # trigger on all branches except for dependabot-triggered push events
    branches-ignore: [ dependabot/** ]
    tags:
      - 'v*'    # trigger on all tags
    paths-ignore:
      - '**.md' # ignore changes in markdown files
  pull_request:
    branches: [ develop ]
    types: [ opened, synchronize, reopened ]

permissions:
  contents: read

jobs:
  test:
    name: Run tests (Node v${{ matrix.node-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18.19, 20.13]

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0  # Get all history and branches

      - name: Set up node ${{ matrix.node-version}}
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # ratchet:actions/setup-node@v4.2.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up corepack (for getting yarn)
        run: corepack enable

      - name: Get yarn cache ${{ matrix.node-version}}
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # ratchet:actions/setup-node@v4.2.0
        with:
          cache: 'yarn'

      - name: yarn install dependencies
        run: |
          yarn install  --immutable

      - name: Run CI tests
        run: |
          yarn test

      - name: Test build
        continue-on-error: false
        run: |
          yarn build
