name: CI Workflow

on:
  push:
    # trigger on all branches except for dependabot-triggered push events
    branches-ignore: [ dependabot/** ]
    tags:
      - 'v*'    # trigger on all tags
    paths-ignore:
      - '**.md' # ignore changes in markdown files
  pull_request:
    branches: [ develop ]
    types: [ opened, synchronize, reopened ]

permissions:
  contents: read

jobs:
  test:
    name: Run tests (Node v${{ matrix.node-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18.19, 20.13]

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: Checkout repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0  # Get all history and branches

      - name: Set up node ${{ matrix.node-version}}
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # ratchet:actions/setup-node@v4.0.4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up corepack (for getting yarn)
        run: corepack enable

      - name: Get yarn cache ${{ matrix.node-version}}
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # ratchet:actions/setup-node@v4.0.4
        with:
          cache: 'yarn'

      - name: yarn install dependencies
        run: |
          yarn install  --immutable

      - name: Run CI tests
        run: |
          yarn test

      - name: Test build
        continue-on-error: false
        run: |
          yarn build
